steps:
# This step runs the unit tests on the app
- name: 'docker.io/library/python:3.7'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install -t /workspace/lib -r requirements.txt && pytest functions/*_test.py'
- name: "gcr.io/cloud-builders/gcloud"
  id: Deploy
  args: ["app", "deploy"]
timeout: "1600s"